# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Achievements
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["23", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: images/metrics_plugin_achievements.svg
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_ignored: 
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
