name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      
          plugin_wakatime_days: 30                                   
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os         
          plugin_wakatime_limit: 4                                  
          plugin_wakatime_url: https://wakatime.com                 
          plugin_wakatime_user: Vault108                         
          plugin_lines: yes  
          plugin_activity: yes
          plugin_activity_limit: 5   
          plugin_activity_days: 14    
          plugin_activity_filter: all    
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
 
