# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Vault108
          template: classic
          base: header, activity, metadata
          base_indepth: yes
          config_display: large
          config_octicon: yes
          config_presets: ocean-blue
          config_timezone: America/New_York
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_ignored: Follower,Gister,Maintainer,Chatter,Verified
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 10
          plugin_habits_languages_threshold: 0%
          plugin_habits_skipped: HASHCAT-DEMO
          plugin_lines: yes
          plugin_lines_history_limit: 30
          plugin_lines_repositories_limit: 5
          plugin_lines_sections: repositories 
          plugin_lines_skipped: HASHCAT-DEMO
