# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: dailydotdev/action-devcard@2.0.4
        with:
         devcard_id: ${{ secrets.DEVCARD_ID }}
   
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Vault108
          template: classic
          base: header, activity, repositories
          config_timezone: America/New_York
          plugin_code: yes
          plugin_code_lines: 12
          plugin_code_load: 100
          plugin_code_visibility: public
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      
          plugin_wakatime_days: 30                                   
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os         
          plugin_wakatime_limit: 4                                  
          plugin_wakatime_url: https://wakatime.com                 
          plugin_wakatime_user: Vault108
         
